### POST authenticate
POST http://localhost:4040/api/auth
content-type: application/json

{
  "username": "admin",
  "password": "1234"
}

### GET product by id
GET http://localhost:4040/api/products/50
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTYxODU4NTMzNCwiZXhwIjoxNjE4NTg4OTM0fQ.kOT-P2rgf7d45S7gjGdAx8ydfSe_6-zPGCPGVPX0iLY

### GET all products
GET http://localhost:4040/api/products/all

### GET all products
GET http://localhost:4040/api/products/category/1

### GET all products with stock less than
GET http://localhost:4040/api/products?maxStock=100

### POST create or update object
POST http://localhost:4040/api/products
content-type: application/json

{
  "id": 51,
  "productName": "Té de café",
  "categoryId": 2,
  "price": 10000.00,
  "stock": 5,
  "active": true
}

### DELETE product by id
DELETE http://localhost:4040/api/products/52